name: Check Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Insert Empty key file
        run : |
          cd src/main/kotlin/com/easternkite/remain/ai
          echo APP_KEY = aaabbb > local.properties
          echo REST_API_KEY = aaabbb > local.properties

      - name: Check Test
        run: ./gradlew test --no-configuration-cache